### ISSUE TITLE
Debug Tool導入

### ISSUE THREAD

**Issue by ho2ri2s** [TechCafeFreedom/TODONE#15]
## Kind (Required)

- Improvement

 ## Overview (Required)

- Introduce Debug Tool
  - Hyperion
  - LeekCanary
  - Stetho

 ## Links	

- Hyperion
  - https://qiita.com/takahirom/items/2f6557f945ddd7c5e074#%E5%B0%8E%E5%85%A5pull-request

**Comment by b4tchkn** [comment]
https://github.com/TechCafeFreedom/TODONE/pull/92
これ終わったらこいつもcloseできそうかね

**Comment by ho2ri2s** [comment]
Dangerとは関係ないぞよ
StethoとかLeakCanaryいれなくて良い感あるしcloseしちゃう
