### ISSUE TITLE
Room導入

### ISSUE THREAD

**Issue by ho2ri2s** [TechCafeFreedom/TODONE#18]
## Kind (Required)

Choose the suitable template if exists.

- Proposal 

 ## Overview (Required)

- SQLiteデータベースを使うためRoomを導入
 ## Links	

- [codelabs](https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#0)
- [誰かの記事](https://codechacha.com/ja/android-jetpack-room/)

**Comment by b4tchkn** [comment]
これって，https://github.com/TechCafeFreedom/TODONE/pull/54 このへんですでに終わってたりする…？

**Comment by felix925** [comment]
あ、おわっちゃってます..！
あとは時々の要望に合わせて改修とテストコードなので閉めちゃいますか....？

**Comment by b4tchkn** [comment]
だね！とりあえず導入するという目的は達成できてるからこれはcloseしよう！
今後，追加でRoom関係やることあったらその都度issue作ってやってこう！
てことでcloseしますう
