### ISSUE TITLE
必要な機能を考える

### ISSUE THREAD

**Issue by Izacchi16** [TechCafeFreedom/TODONE#2]
# Kind(Required)
Development stage
# Overview (Required)
- Think about what features you need (This application is TODOList)
- Proceed in parallel with #1

**Comment by b4tchkn** [comment]
I think we need the following features.
- User can see their tasks(HomeFragment?)
<img src="https://user-images.githubusercontent.com/28699251/75735213-7ecd6680-5d3d-11ea-9698-7b8f345441e9.png" width="250px" />
- User can see their tasks separate section(NowFragment?)
<img src="https://user-images.githubusercontent.com/28699251/75735358-d79cff00-5d3d-11ea-868f-412534265530.png" width="250px" />
- User can see notifications(NotificationsFragment?)
<img src="https://user-images.githubusercontent.com/28699251/75735460-0ca95180-5d3e-11ea-8d12-db22b7a5326a.png" width="250px" />
- User can set the app(SettingFragment?)
<img src="https://user-images.githubusercontent.com/28699251/75735578-56923780-5d3e-11ea-8a6b-eaa0a32e6141.png" width="250px" />

**Comment by Izacchi16** [comment]
**features plan**

Regarding screen transitions, we will reproduce it with a prototype of Figma(WIP)

1. Drawer has Items that jump to settings, button to switch dark theme, etc.
2.  BottomNav has 3 items Home,Now and Notifications
3. Whether the action button to add TODO is FAB or put on the upper right like the image above
4. Regarding the profile, let's arrange it in a circle at the top of the Drawer (like Twitter)
