### ISSUE TITLE
Setting CI

### ISSUE THREAD

**Issue by ho2ri2s** [TechCafeFreedom/TODONE#4]
# OverView
- Setting [Bitrise](https://www.bitrise.io/)
  - This is CI that can manipulate with GUI.
- Setting [ktlint](https://github.com/pinterest/ktlint)
  - This is check format for Kotlin.
- Setting Danger
  - This is useful for review.
  - Click [here](https://qiita.com/hkusu/items/e1bd99efa92263f448ff) for details.

This is my selfish opinion.
You can use other tool for free !

**Comment by b4tchkn** [comment]
I used Bitrise so can I close this issue?

**Comment by ho2ri2s** [comment]
Nice!
I will set up ktlint and Danger today, so after that,  please close this issue👍

**Comment by b4tchkn** [comment]
これはどうなった？？

**Comment by ho2ri2s** [comment]
あとDangerだけだす！
